// // /*
// // Auto-generated by: https://github.com/pmndrs/gltfjsx
// // Command: npx gltfjsx@6.5.3 public/model.glb -o src/LampModeln.jsx
// // Author: TadenStar (https://sketchfab.com/tadenstar)
// // License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// // Source: https://sketchfab.com/3d-models/moon-table-lamp-9af2f6a821fe440bbdf6f3819f8168ee
// // Title: Moon - Table lamp
// // */

// // import React from 'react'
// // import { useGLTF } from '@react-three/drei'

// // export function Model(props) {
// //   const { nodes, materials } = useGLTF('/model.glb')
// //   return (
// //     <group {...props} dispose={null}>
// //       <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
// //         <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
// //           <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
// //             <mesh geometry={nodes.Wood_Cage_Wood_0.geometry} material={materials.Wood} />
// //             <mesh geometry={nodes.Moon_Moon_0.geometry} material={materials.Moon} />
// //           </group>
// //         </group>
// //       </group>
// //     </group>
// //   )
// // }

// // useGLTF.preload('/model.glb')

// import React, { useRef, useLayoutEffect } from "react";
// import { useGLTF, useScroll } from "@react-three/drei";
// import { useFrame } from "@react-three/fiber";
// import * as THREE from "three";

// export function Model(props) {
//   // 1. Load the model
//   const { nodes, materials } = useGLTF("/model.glb");
//   const group = useRef();
//   const scroll = useScroll();

//   // 2. Configure the "Moon" material for glowing
//   useLayoutEffect(() => {
//     // We specificially target 'materials.Moon' because we saw it in your auto-generated code
//     if (materials.Moon) {
//       materials.Moon.emissive = new THREE.Color("white");
//       materials.Moon.emissiveIntensity = 0; // Start off
//       materials.Moon.toneMapped = false; // Allows bright bloom
//     }
//   }, [materials]);

//   // 3. Animation Loop
//   useFrame((state, delta) => {
//     const offset = scroll.offset; // 0 to 1

//     // A. Rotate the lamp
//     // We rotate the ref 'group' which holds the whole object
//     if (group.current) {
//       group.current.rotation.y = THREE.MathUtils.damp(
//         group.current.rotation.y,
//         offset * Math.PI * 2, // Full spin
//         2,
//         delta,
//       );
//     }

//     // B. Light Up Effect
//     if (materials.Moon) {
//       // Lerp intensity from 0 (off) to 3 (bright)
//       materials.Moon.emissiveIntensity = THREE.MathUtils.lerp(0, 5, offset);
//     }
//   });

//   return (
//     // We attach the 'group' ref here to rotate the whole thing
//     <group ref={group} {...props} dispose={null}>
//       {/* CRITICAL FIX:
//          We are using the EXACT nesting structure from your auto-generated code.
//          This preserves the correct Scale and Rotation from the original 3D file.
//       */}
//       <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
//         <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
//           <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
//             {/* The Wood Frame */}
//             <mesh
//               castShadow
//               receiveShadow
//               geometry={nodes.Wood_Cage_Wood_0.geometry}
//               material={materials.Wood}
//             />

//             {/* The Moon Bulb (This is what glows) */}
//             <mesh
//               geometry={nodes.Moon_Moon_0.geometry}
//               material={materials.Moon}
//             />
//           </group>
//         </group>
//       </group>
//     </group>
//   );
// }

// useGLTF.preload("/model.glb");

// abv is working
import React, { useRef, useLayoutEffect } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export function Model({ isDarkMode, ...props }) {
  const { nodes, materials } = useGLTF("/model.glb");
  const group = useRef();
  const scroll = useScroll();

  useLayoutEffect(() => {
    if (materials.Moon) {
      materials.Moon.toneMapped = false;
      materials.Moon.transparent = true;
    }
  }, [materials]);

  useFrame((state, delta) => {
    const r = scroll.offset;

    // 1. Rotation (Spins as it rises)
    if (group.current) {
      group.current.rotation.y = -r * Math.PI * 1;
    }

    // 2. Glow Effect
    if (materials.Moon) {
      // Dark Mode: Bright Orange Glow
      // Light Mode: Subtle Warm Glow
      const maxIntensity = isDarkMode ? 5 : 2;
      materials.Moon.emissiveIntensity = THREE.MathUtils.lerp(
        0,
        maxIntensity,
        r,
      );

      // Color Shift
      const targetColor = isDarkMode
        ? new THREE.Color("#ffaa00")
        : new THREE.Color("#ffddaa");
      materials.Moon.emissive.lerp(targetColor, 0.1);
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      {/* Structure based on your working code */}
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wood_Cage_Wood_0.geometry}
              material={materials.Wood}
            />
            <mesh
              geometry={nodes.Moon_Moon_0.geometry}
              material={materials.Moon}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/model.glb");
